---
# Add this as an override to produce duo data
# ex: docker-compose -f docker-compose.yml -f spooldir/duo.yml up -d
version: '3'
services:
  duo:
    image: confluentinc/cp-server-connect-base:latest
    hostname: duo
    container_name: duo
    user: root
    depends_on:
      - broker
    volumes:
      - ./spooldir/:/var/spooldir/
      - ./scripts/:/tmp/scripts/
    command:
      - /tmp/scripts/produceDuoData.sh
